server:
  port: 443
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: star123
    key-store-password: star123